added controller, dto, mapper
SvNadorozhnyi/BookStore pull request #2
Opened 2024-10-25 22:38 UTC by SvNadorozhnyi

2024-10-26 08:27 UTC, okuzan requested changes

2024-10-26 08:27 UTC, okuzan commented on src/main/java/org/example/bookstore/dto/BookDto.java
> +@Component
```suggestion
```

2024-10-26 16:12 UTC, Elena-Bruyako requested changes
just two comments

2024-10-26 16:12 UTC, Elena-Bruyako commented on pom.xml
> +            <version>3.3.5</version>
remove version
```suggestion
```

2024-10-26 16:12 UTC, Elena-Bruyako commented on src/main/java/org/example/bookstore/repository/impl/BookRepositoryImpl.java
> +        }
add catch block

2024-10-27 09:19 UTC, okuzan approved these changes

2024-10-28 23:27 UTC, merged