added liquibase support, implemented soft delete concept, added new endpoint
SvNadorozhnyi/BookStore pull request #3
Opened 2024-11-08 20:06 UTC by SvNadorozhnyi

2024-11-09 08:22 UTC, Elena-Bruyako requested changes
see comments

2024-11-09 08:22 UTC, Elena-Bruyako commented on pom.xml
> +            <version>4.29.2</version>
```suggestion
            <version>${liquibase.version}</version>
```

2024-11-09 08:22 UTC, Elena-Bruyako commented on pom.xml
> +            <version>4.29.2</version>
```suggestion
            <version>${liquibase.version}</version>
```

2024-11-09 08:22 UTC, Elena-Bruyako commented on src/main/java/org/example/bookstore/controller/BookController.java
> +    public BookDto updateBookById(@PathVariable Long id, @RequestBody BookDto bookDto) {
```suggestion
    public BookDto updateBookById(@PathVariable Long id, @RequestBody CreateBookRequestDto bookDto) {
```

2024-11-09 08:22 UTC, Elena-Bruyako commented on src/main/java/org/example/bookstore/model/Book.java
>  @Data
Don't use @Data for entities

```suggestion
```

2024-11-09 08:22 UTC, Elena-Bruyako commented on src/main/java/org/example/bookstore/service/impl/BookServiceImpl.java
> +        }
```suggestion
        Book book = bookRepository.findById(id)
                .orElseThrow(()....
        bookMapper.updateBookFromDto(bookDto, book);
        return bookMapper.toDto(bookRepository.save(book));
```

2024-11-11 09:34 UTC, liliia-ponomarenko approved these changes
Awesome 😎

2024-11-11 09:34 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/01-create-book-table.yaml
> +                    nullable: false
add one empty line to the end of the file (check other files)

2024-11-11 19:02 UTC, merged